import { Scenario } from "../scenario";
import { StationGraphMap } from "../station-graph-map";

/**
 * TAO-095 - Base HORUS
 * 
 * Planeta classe-M com 7 luas em órbita nomeadas após deidades egípcias.
 * Base científica/militar HORUS na superfície.
 * Comunicações incluem diálogos sobre ocultismo, ciência, mechas e filosofia.
 */
export const tao095 = (): Scenario => {
  const baseMap = new StationGraphMap({
    levels: [
      {
        rooms: ["HANGAR_PRINCIPAL", null, "HANGAR_SECUNDARIO"],
      },
      {
        rooms: [
          {
            id: "AIRLOCK_NORTE",
            type: "airlock",
            pressureLossRisk: false,
          },
          null,
          {
            id: "AIRLOCK_SUL",
            type: "airlock",
            pressureLossRisk: false,
          },
        ],
      },
      { rooms: ["COMANDO", "CORREDOR_PRINCIPAL", "COMUNICACOES"] },
      { rooms: ["OBSERVATORIO", "SALA_OPS", "LAB_PRINCIPAL"] },
      { rooms: ["ALOJAMENTOS_A", "REFEITORIO", "ALOJAMENTOS_B"] },
      { rooms: ["ARMORY", "DEPOSITO", "ENFERMARIA"] },
      { rooms: ["GERADORES", "SALA_CONTROLE", "MANUTENCAO"] },
      { rooms: [null, "NUCLEO_REATOR", null] },
      { rooms: [null, "SUBTERRANEO", null] },
    ],
    connections: [
      { from: "HANGAR_PRINCIPAL", to: "AIRLOCK_NORTE", password: "HORUS-TAO" },
      { from: "HANGAR_SECUNDARIO", to: "AIRLOCK_SUL", defaultOpen: true },
      { from: "AIRLOCK_NORTE", to: "CORREDOR_PRINCIPAL" },
      { from: "AIRLOCK_SUL", to: "CORREDOR_PRINCIPAL" },
      { from: "CORREDOR_PRINCIPAL", to: "COMANDO" },
      { from: "CORREDOR_PRINCIPAL", to: "COMUNICACOES" },
      { from: "COMANDO", to: "OBSERVATORIO" },
      { from: "CORREDOR_PRINCIPAL", to: "SALA_OPS" },
      { from: "COMUNICACOES", to: "LAB_PRINCIPAL" },
      { from: "OBSERVATORIO", to: "SALA_OPS" },
      { from: "SALA_OPS", to: "LAB_PRINCIPAL" },
      { from: "OBSERVATORIO", to: "ALOJAMENTOS_A" },
      { from: "SALA_OPS", to: "REFEITORIO" },
      { from: "LAB_PRINCIPAL", to: "ALOJAMENTOS_B" },
      { from: "ALOJAMENTOS_A", to: "REFEITORIO" },
      { from: "REFEITORIO", to: "ALOJAMENTOS_B" },
      { from: "ALOJAMENTOS_A", to: "ARMORY" },
      { from: "REFEITORIO", to: "DEPOSITO" },
      { from: "ALOJAMENTOS_B", to: "ENFERMARIA" },
      { from: "ARMORY", to: "DEPOSITO" },
      { from: "DEPOSITO", to: "ENFERMARIA" },
      { from: "ARMORY", to: "GERADORES" },
      { from: "DEPOSITO", to: "SALA_CONTROLE" },
      { from: "ENFERMARIA", to: "MANUTENCAO" },
      { from: "GERADORES", to: "SALA_CONTROLE" },
      { from: "SALA_CONTROLE", to: "MANUTENCAO" },
      { from: "SALA_CONTROLE", to: "NUCLEO_REATOR", password: "REACTOR-ACCESS" },
      { from: "NUCLEO_REATOR", to: "SUBTERRANEO", password: "DEEP-VAULT" },
    ],
    diagnostics: {
      title: "SISTEMA DE DIAGNÓSTICO - BASE HORUS // TAO-095",
      messages: [
        { type: "notice", message: "╔═══════════════════════════════════════════════════════════════════╗" },
        { type: "notice", message: "║           SISTEMA DE DIAGNÓSTICO - BASE HORUS v3.6c              ║" },
        { type: "notice", message: "║               PLANETA TAO-095 // 7 LUAS EGÍPCIAS                  ║" },
        { type: "notice", message: "╚═══════════════════════════════════════════════════════════════════╝" },
        { type: "notice", message: "" },
        {
          type: "check",
          message: ">>> INICIALIZANDO SISTEMAS DA BASE",
          status: "OK",
          delay: 1800,
        },
        { type: "notice", message: "" },
        ...(Math.random() > 0.6
          ? [
              { type: "notice" as const, message: "┌─ CANAL DE COMUNICAÇÃO - 10 USUÁRIOS CONECTADOS ──────────────────┐" },
              { type: "notice" as const, message: "│ [DR. HELENA]: Os hieróglifos em THOTH desafiam todas as teorias│" },
              { type: "notice" as const, message: "│               Não são egípcios... são anteriores à humanidade.   │" },
              { type: "notice" as const, message: "│ [ENG. KLAUS]: Datação radiométrica confirma: 47.000 anos AP.    │" },
              { type: "notice" as const, message: "│ [PILOTO AKIRA]: Meu Titan-class detectou interferência quântica │" },
              { type: "notice" as const, message: "│                 próximo à lua ISIS. Navegação comprometida.      │" },
              { type: "notice" as const, message: "│ [PROF. YUKI]: Filosofia hermética: 'Como acima, assim abaixo.'  │" },
              { type: "notice" as const, message: "│               As luas formam um mapa estelar codificado.         │" },
              { type: "notice" as const, message: "│ [TECH. MARCUS]: Reator ressonando em 432Hz. Frequência cósmica. │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]
          : [
              { type: "notice" as const, message: "┌─ CANAL DE COMUNICAÇÃO - 10 USUÁRIOS CONECTADOS ──────────────────┐" },
              { type: "notice" as const, message: "│ [DR. HELENA]: Gente, achei um hieróglifo que parece o Ednaldo   │" },
              { type: "notice" as const, message: "│               Pereira. COINCIDÊNCIA? ACHO QUE NÃO.               │" },
              { type: "notice" as const, message: "│ [ENG. KLAUS]: Carai Cleitin, o reator tá fazendo barulho de Zap│" },
              { type: "notice" as const, message: "│               notificação. É o Zap, é o Zaaap! 📱                │" },
              { type: "notice" as const, message: "│ [PILOTO AKIRA]: Calma Calabreso, o Titan tá dançando sozinho.  │" },
              { type: "notice" as const, message: "│                 Acho que instalaram Spotify nele kkkkkkkk        │" },
              { type: "notice" as const, message: "│ [PROF. YUKI]: Ué Cleitin, as luas formam a logo do Flamengo??? │" },
              { type: "notice" as const, message: "│ [TECH. MARCUS]: Para de tomar refri e vem arrumar isso aqui!!!  │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]),
        { type: "notice" as const, message: "" },
        ...(Math.random() > 0.5
          ? [
              { type: "notice" as const, message: "┌─ TRANSMISSÃO CIFRADA DETECTADA ──────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [∴ INITIATUS-7 ∴]: Ordo ab chao. Lux in tenebris lucet.         │" },
              { type: "notice" as const, message: "│ [∴ MAGISTER-3 ∴]: Solve et coagula. Visita interiora terrae.    │" },
              { type: "notice" as const, message: "│ [∴ ADEPTUS-11 ∴]: Scientia potentia est. Fiat lux.              │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]
          : [
              { type: "warning" as const, message: "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" },
              { type: "warning" as const, message: "⚠ USUÁRIO DESCONHECIDO: DADOS CRIPTOGRAFADOS ⚠" },
              { type: "warning" as const, message: "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" },
            ]),
        { type: "notice" as const, message: "" },
        {
          type: "check" as const,
          message: ">> Verificando integridade estrutural",
          status: "OK",
          delay: 1500,
        },
        { type: "notice" as const, message: "   └─ Casco pressurizado: 100%" },
        { type: "notice" as const, message: "   └─ Escudos atmosféricos: OPERACIONAIS" },
        { type: "notice" as const, message: "   └─ Sensores sísmicos: ATIVOS" },
        { type: "notice" as const, message: "" },
        ...(Math.random() > 0.6
          ? [
              { type: "notice" as const, message: "┌─ DISCUSSÃO ATIVA ────────────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [DR. SANTOS]: Carl Jung estava certo sobre o inconsciente       │" },
              { type: "notice" as const, message: "│               coletivo. A sincronicidade dos eventos...          │" },
              { type: "notice" as const, message: "│ [OPERADORA ZHEN]: Meu mecha perdeu 3 segundos durante a         │" },
              { type: "notice" as const, message: "│                   aproximação de OSIRIS. Dilatação temporal!     │" },
              { type: "notice" as const, message: "│ [DR. AMARA]: Não é física. É alquimia pura. Transmutação da    │" },
              { type: "notice" as const, message: "│              matéria através da consciência.                     │" },
              { type: "notice" as const, message: "│ [PILOTO KENJI]: Shogun-Type registrou entidades não-corpóreas   │" },
              { type: "notice" as const, message: "│                 em NEPHTHYS. Espectros ou projeções psíquicas?   │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]
          : [
              { type: "notice" as const, message: "┌─ DISCUSSÃO ATIVA ────────────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [DR. SANTOS]: Gente, o Carl Jung PODE ter sido o Casimiro do   │" },
              { type: "notice" as const, message: "│               século passado. Change my mind. 🤔                 │" },
              { type: "notice" as const, message: "│ [OPERADORA ZHEN]: Opa eae mem, meu mecha travou no Windows XP!  │" },
              { type: "notice" as const, message: "│                   AQUELE SOM: turu ru ru ruuu 💀                 │" },
              { type: "notice" as const, message: "│ [DR. AMARA]: Vai Brasília! Descobri que alquimia é só química  │" },
              { type: "notice" as const, message: "│              com filtro do Instagram kkkkkk                      │" },
              { type: "notice" as const, message: "│ [PILOTO KENJI]: Os fantasmas em NEPHTHYS estão cantando 'Ó o   │" },
              { type: "notice" as const, message: "│                 gás' 😂😂😂 Não aguento mais esse planeta!         │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]),
        { type: "notice" as const, message: "" },
        {
          type: "check" as const,
          message: ">> Sistema de energia",
          status: "ONLINE",
          delay: 1600,
        },
        { type: "notice" as const, message: `   └─ Reator de fusão: ${Math.floor(Math.random() * 8) + 91}% capacidade` },
        { type: "notice" as const, message: "   └─ Células de backup: 100% carga" },
        { type: "notice" as const, message: `   └─ Consumo: ${Math.floor(Math.random() * 15) + 68}% do total` },
        { type: "notice" as const, message: "" },
        ...(Math.random() > 0.6
          ? [
              { type: "notice" as const, message: "┌─ RELATÓRIO CIENTÍFICO ───────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [ASTROFÍSICA NOVA]: Órbitas das luas formam um pentagrama       │" },
              { type: "notice" as const, message: "│                     perfeito visto do polo norte. Impossível.    │" },
              { type: "notice" as const, message: "│ [ENG. DMITRI]: Não é fenômeno natural. Engenharia pré-humana.   │" },
              { type: "notice" as const, message: "│ [ARQUEÓLOGA ISIS]: O Kybalion estava correto: 'Tudo é mente.'   │" },
              { type: "notice" as const, message: "│ [MEC. TESLA]: Thunderbolt captou frequências de 7.83Hz. A       │" },
              { type: "notice" as const, message: "│               ressonância Schumann. O batimento do planeta.      │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]
          : [
              { type: "notice" as const, message: "┌─ RELATÓRIO CIENTÍFICO ───────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [ASTROFÍSICA NOVA]: As luas tão dançando 'Aquecimento Global' do│" },
              { type: "notice" as const, message: "│                     Pabllo Vittar. CIÊNCIA NÃO EXPLICA!!!        │" },
              { type: "notice" as const, message: "│ [ENG. DMITRI]: Blyat! Encontrei uma inscrição: 'Cê é loko meu'  │" },
              { type: "notice" as const, message: "│                em cirílico antigo. COMO??? 🤯                     │" },
              { type: "notice" as const, message: "│ [ARQUEÓLOGA ISIS]: O Kybalion era só um PDF do Clube do Ricardo │" },
              { type: "notice" as const, message: "│ [MEC. TESLA]: Thunderbolt detectou 'Ai ai ai deixa eu me lamber'│" },
              { type: "notice" as const, message: "│               vindo do espaço profundo. Globo Repórter explica!  │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]),
        { type: "notice" as const, message: "" },
        {
          type: "check" as const,
          message: ">> Monitoramento das 7 luas",
          status: "RASTREANDO",
          delay: 1900,
        },
        { type: "notice" as const, message: "   ├─ LUA-01 [ANUBIS]: Órbita estável - 8.3d - Guardião dos Mortos" },
        { type: "notice" as const, message: "   ├─ LUA-02 [OSIRIS]: Órbita estável - 12.7d - Ressurreição" },
        { type: "notice" as const, message: "   ├─ LUA-03 [SETH]: Órbita estável - 18.2d - Caos Primordial" },
        { type: "notice" as const, message: "   ├─ LUA-04 [THOTH]: Órbita estável - 24.9d - Conhecimento Oculto" },
        { type: "notice" as const, message: "   ├─ LUA-05 [RA]: Órbita estável - 31.4d - Disco Solar" },
        { type: "notice" as const, message: "   ├─ LUA-06 [ISIS]: Órbita estável - 39.8d - Magia & Mistérios" },
        { type: "notice" as const, message: "   └─ LUA-07 [NEPHTHYS]: Órbita estável - 47.1d - Morte & Renascer" },
        { type: "notice" as const, message: "" },
        ...(Math.random() > 0.5
          ? [
              { type: "notice" as const, message: "┌─ CANAL ESOTÉRICO ────────────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [∴ HIEROPHANT ∴]: Per aspera ad astra. Stellae cursus docet.    │" },
              { type: "notice" as const, message: "│ [∴ ARCHON ∴]: Cogito ergo sum. Anima mundi revelatur.           │" },
              { type: "notice" as const, message: "│ [∴ SANCTUS ∴]: Veritas vos liberabit. Omnia vincit veritas.     │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]
          : [
              { type: "warning" as const, message: "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" },
              { type: "warning" as const, message: "⚠ USUÁRIO DESCONHECIDO: DADOS CRIPTOGRAFADOS ⚠" },
              { type: "warning" as const, message: "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" },
            ]),
        { type: "notice" as const, message: "" },
        ...(Math.random() > 0.6
          ? [
              { type: "notice" as const, message: "┌─ ANÁLISE FILOSÓFICA ─────────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [PROF. VOLTAIRE]: Se consciência molda realidade, estas ruínas  │" },
              { type: "notice" as const, message: "│                   foram materializadas pelo pensamento coletivo. │" },
              { type: "notice" as const, message: "│ [COMANDANTE HORUS]: Câmara selada encontrada em SETH. Língua    │" },
              { type: "notice" as const, message: "│                     adâmica primordial. Pré-Babel.               │" },
              { type: "notice" as const, message: "│ [DR. CROWLEY]: Thelema: 'Faze o que tu queres há de ser tudo    │" },
              { type: "notice" as const, message: "│                da Lei.' Vontade é manifestação.                  │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]
          : [
              { type: "notice" as const, message: "┌─ ANÁLISE FILOSÓFICA ─────────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [PROF. VOLTAIRE]: Se consciência molda realidade... POR QUE EU  │" },
              { type: "notice" as const, message: "│                   NÃO CONSIGO PARAR DE PENSAR EM PÃO DE ALHO?!  │" },
              { type: "notice" as const, message: "│ [COMANDANTE HORUS]: Achei escrito na câmara: 'Aqui tem Ifood?'  │" },
              { type: "notice" as const, message: "│                     em hieróglifos. Civilization is doomed. 😔   │" },
              { type: "notice" as const, message: "│ [DR. CROWLEY]: 'Faze o que tu queres' mas primeiro curte lá no  │" },
              { type: "notice" as const, message: "│                Insta @horus_base_oficial 🙏 Tmj família!         │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]),
        { type: "notice" as const, message: "" },
        {
          type: "check" as const,
          message: ">> Sistemas de comunicação",
          status: "NOMINAL",
          delay: 1300,
        },
        { type: "notice" as const, message: "   └─ Uplink orbital: CONECTADO" },
        { type: "notice" as const, message: "   └─ Array de longo alcance: OPERACIONAL" },
        { type: "notice" as const, message: "   └─ Quantum-comm: SINCRONIZADO" },
        { type: "notice" as const, message: "" },
        ...(Math.random() > 0.6
          ? [
              { type: "notice" as const, message: "┌─ RELATÓRIO DE CAMPO ─────────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [PILOTO SEKHMET]: Guardian-Type detectou radiação psi em RA.    │" },
              { type: "notice" as const, message: "│                   Energia psíquica em níveis perigosos!          │" },
              { type: "notice" as const, message: "│ [SÁBIA AKASHA]: Registros akáshicos se abrindo. Memória cósmica │" },
              { type: "notice" as const, message: "│                 sendo acessada. O véu está se desfazendo.        │" },
              { type: "notice" as const, message: "│ [MEC. AVALON]: Excalibur ressoou com as ruínas. Reconhecimento  │" },
              { type: "notice" as const, message: "│                ancestral. Como se já tivesse estado aqui.        │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]
          : [
              { type: "notice" as const, message: "┌─ RELATÓRIO DE CAMPO ─────────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [PILOTO SEKHMET]: Guardian detectou uma voz gritando 'É TETRA!  │" },
              { type: "notice" as const, message: "│                   É PENTAAAA!' vindo da lua RA. Socorro! 😱      │" },
              { type: "notice" as const, message: "│ [SÁBIA AKASHA]: Os registros akáshicos têm uma pasta 'memes.zip'│" },
              { type: "notice" as const, message: "│                 com 47GB. A humanidade sempre foi assim...       │" },
              { type: "notice" as const, message: "│ [MEC. AVALON]: Excalibur começou a tocar 'Sou Foda' do Baco    │" },
              { type: "notice" as const, message: "│                Exu sozinho. EU NÃO FIZ NADA!!! 🎵                │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]),
        { type: "notice" as const, message: "" },
        {
          type: "check" as const,
          message: ">> Sistemas de defesa",
          status: "ARMADO",
          delay: 1400,
        },
        { type: "warning" as const, message: "   ├─ Ponto de defesa #3: Manutenção programada" },
        { type: "notice" as const, message: "   ├─ Sistema anti-orbital: PRONTO" },
        { type: "notice" as const, message: "   └─ Blindagem eletromagnética: 89% eficiência" },
        { type: "notice" as const, message: "" },
        ...(Math.random() > 0.5
          ? [
              { type: "notice" as const, message: "┌─ TRANSMISSÃO HERMÉTICA ──────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [∴ ILLUMINATUS ∴]: Aurum nostrum non est aurum vulgi.           │" },
              { type: "notice" as const, message: "│ [∴ FRATER ∴]: Tabula smaragdina revelat magnum mysterium.       │" },
              { type: "notice" as const, message: "│ [∴ SOROR ∴]: In somniis anima veritatem invenit sempiternam.    │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]
          : [
              { type: "warning" as const, message: "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" },
              { type: "warning" as const, message: "⚠ USUÁRIO DESCONHECIDO: DADOS CRIPTOGRAFADOS ⚠" },
              { type: "warning" as const, message: "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" },
            ]),
        { type: "notice" as const, message: "" },
        {
          type: "check" as const,
          message: ">> Verificação de tripulação",
          status: "OK",
          delay: 1100,
        },
        { type: "notice" as const, message: "   └─ Pessoal presente: 47 de 65" },
        { type: "notice" as const, message: "   └─ Equipes de campo ativas: 4" },
        { type: "notice" as const, message: `   └─ Missões em andamento: ${Math.floor(Math.random() * 3) + 2}` },
        { type: "notice" as const, message: "" },
        ...(Math.random() > 0.6
          ? [
              { type: "notice" as const, message: "┌─ CONCLUSÃO METAFÍSICA ───────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [DR. JUNG]: Arquétipos universais manifestos. O inconsciente    │" },
              { type: "notice" as const, message: "│             coletivo se revela através das sincronicidades.      │" },
              { type: "notice" as const, message: "│ [TODOS]: As 7 luas não são satélites. São portais. Chaves.      │" },
              { type: "notice" as const, message: "│          Cada uma guarda um fragmento do Conhecimento Proibido.  │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]
          : [
              { type: "notice" as const, message: "┌─ CONCLUSÃO METAFÍSICA ───────────────────────────────────────────┐" },
              { type: "notice" as const, message: "│ [DR. JUNG]: O inconsciente coletivo é tipo o grupo da família   │" },
              { type: "notice" as const, message: "│             no Zap: ninguém pediu mas tá todo mundo lá.          │" },
              { type: "notice" as const, message: "│ [TODOS]: As 7 luas não são satélites. São as 7 coxinhas da festa│" },
              { type: "notice" as const, message: "│          Cada uma tem um sabor: frango, carne, queijo... REFRI!  │" },
              { type: "notice" as const, message: "└──────────────────────────────────────────────────────────────────┘" },
            ]),
        { type: "notice" as const, message: "" },
        { type: "notice" as const, message: "╔═══════════════════════════════════════════════════════════════════╗" },
        {
          type: "summary",
          message: "║   STATUS: SISTEMAS OPERACIONAIS - BASE HORUS ONLINE               ║",
        },
        { type: "notice", message: "║   AVISO: ANOMALIAS QUÂNTICAS DETECTADAS NAS 7 LUAS               ║" },
        { type: "notice", message: "╚═══════════════════════════════════════════════════════════════════╝" },
        { type: "notice", message: "" },
        { type: "notice", message: "// Conectando ao sistema principal..." },
        {
          type: "notice",
          message: `// IP: ${(Math.random() * 2000 + 1000).toFixed(0)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}`,
        },
      ],
    },
  });

  const scenario: Scenario = {
    id: "TAO-095",
    name: "TAO-095 // HORUS",
    type: "planet",
    crew: { current: 47, capacity: 65 },
    adminCredentials: { username: "HORUS-ADMIN", password: "COMP-CON-7" },
    charts: ["oxygen", "temperature", "pressure"],
    stats: {
      planeta: "TAO-095 (Classe-M)",
      diâmetro: "12.742 km",
      gravidade: "1.02 g",
      atmosfera: "Respirável (N2/O2)",
      luas: "7 satélites naturais",
      pressão: "1.01 bar",
    },
    exteriorStats: [
      {
        type: "surfaceTemp",
        label: "TEMPERATURA SUPERFÍCIE",
        unit: "°C",
        defaultValue: Array(30).fill(22),
        min: 18,
        max: 28,
        isArray: true,
      },
      {
        type: "atmosphericAnalysis",
        label: "COMPOSIÇÃO ATM.",
        unit: "%",
        defaultValue: 78,
      },
      {
        type: "radiationLevel",
        label: "RADIAÇÃO SOLAR",
        unit: "mSv/h",
        defaultValue: Array(30).fill(0.3),
        min: 0.2,
        max: 0.5,
        isArray: true,
      },
      {
        type: "windSpeed",
        label: "VELOCIDADE VENTO",
        unit: "km/h",
        defaultValue: Array(30).fill(15),
        min: 5,
        max: 35,
        isArray: true,
      },
      {
        type: "humidity",
        label: "UMIDADE",
        unit: "%",
        defaultValue: Array(30).fill(62),
        min: 45,
        max: 75,
        isArray: true,
      },
      {
        type: "rotationSpeed",
        label: "LUAS RASTREADAS",
        unit: "sat",
        defaultValue: 7,
      },
    ],
    map: baseMap,
    systemLogs: [
      { time: "09.12.9000 08:15", message: "Base HORUS - Inicialização de turno concluída" },
      { time: "09.12.9000 12:44", message: "LUA-05 [RA] - Alinhamento orbital detectado" },
      { time: "10.12.9000 03:22", message: `BACKUP horus_${Math.floor(Math.random() * 9999).toString().padStart(4, '0')}.dat CONCLUÍDO` },
      { time: "10.12.9000 14:17", message: "Equipe de reconhecimento retornou - setor norte" },
      { time: "11.12.9000 07:38", message: `ARQUIVO orbital_${Math.floor(Math.random() * 9999).toString().padStart(4, '0')}.log CRIADO` },
      { time: "11.12.9000 19:55", message: "Manutenção preventiva - ponto de defesa #3" },
      { time: "12.12.9000 06:11", message: "Tempestade magnética detectada - sistemas compensando" },
      { time: "13.12.9000 04:29", message: "Uplink com satélite orbital restabelecido" },
    ],
    controlButtons: [
      {
        label: "ESCUDOS BASE",
        defaultState: true,
        restricted: true,
        type: "toggle",
        linkedRoom: "SALA_CONTROLE",
      },
      {
        label: "SENSORES ORBITAIS",
        defaultState: true,
        restricted: false,
        type: "toggle",
        linkedRoom: "OBSERVATORIO",
      },
      {
        label: "DEFESAS ATIVAS",
        defaultState: true,
        restricted: true,
        type: "toggle",
        toggleStates: {
          true: "ARMADO",
          false: "DESARMADO",
        },
        linkedRoom: "ARMORY",
      },
      {
        label: "HANGAR PRINCIPAL",
        defaultState: false,
        restricted: true,
        type: "toggle",
        toggleStates: {
          true: "DESTRANCADO",
          false: "TRANCADO",
        },
        linkedRoom: "HANGAR_PRINCIPAL",
      },
      {
        label: "PURGA EMERGENCIAL",
        defaultState: false,
        restricted: true,
        type: "action",
        function: "emergency",
      },
      {
        label: "DADOS-ESTAÇÃO",
        defaultState: false,
        restricted: false,
        type: "action",
      },
    ],
    theme: "horus",
  };

  return scenario;
};
